[package]
name = "ejs"
version = "0.1.0"
edition = "2024"

[features]
default = ["qjs", "boa"]
qjs = ["rquickjs"]
boa = ["boa_engine", "boa_gc"]

[dependencies]
swc_ecma_parser = "28"
swc_ecma_ast = "19"
swc_ecma_codegen = "21"
swc_common = { version = "18", features = ["tty-emitter"] }
swc_atoms = "9"
rquickjs = { version = "0.10", optional = true }
boa_engine = { version = "0.21", optional = true }
boa_gc = { version = "0.21", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[target.'cfg(all(not(target_os = "windows"), not(target_os = "android"), not(target_env = "musl")))'.dependencies]
snmalloc-rs = { version = "0.3", features = [
  "default",
  "lto",
], default-features = false }

[profile.release]
debug = false
lto = true
strip = true
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.bloaty]
debug = true
lto = false
strip = false
inherits = 'release'
